-- Exercise media URLs migration
-- Generated by populate-exercise-media.mjs

-- [1] Bench Press → Bench Press (score: 100)
UPDATE exercises SET image_url = 'https://cdn.exercisedb.dev/media/w/images/MKspzx3H3T.jpg', gif_url = 'https://cdn.exercisedb.dev/w/videos/N75Uemp/41n2hxnFMotsXTj3__Barbell-Bench-Press_Chest2_.mp4', exercisedb_id = 'exr_41n2hxnFMotsXTj3' WHERE id = 1;
-- [2] Incline Dumbbell Press → Dumbbell Incline One Arm Hammer Press (score: 60)
UPDATE exercises SET image_url = 'https://cdn.exercisedb.dev/media/w/images/EEeXEu5x2b.jpg', gif_url = 'https://cdn.exercisedb.dev/w/videos/cCtHUc4/41n2haNJ3NA8yCE2__Dumbbell-Incline-One-Arm-Hammer-Press_Upper-Arms_.mp4', exercisedb_id = 'exr_41n2haNJ3NA8yCE2' WHERE id = 2;
-- [4] Dips → Triceps Dips Floor (score: 80)
UPDATE exercises SET image_url = 'https://cdn.exercisedb.dev/media/w/images/HvLpzpKzge.jpg', gif_url = 'https://cdn.exercisedb.dev/w/videos/A0jMsUc/41n2hHH9bNfi98YU__Triceps-Dips-Floor_Upper-Arms.mp4', exercisedb_id = 'exr_41n2hHH9bNfi98YU' WHERE id = 4;
-- [6] Deadlift → Dumbbell Stiff Leg Deadlift (score: 80)
UPDATE exercises SET image_url = 'https://cdn.exercisedb.dev/media/w/images/5zfJekr2FH.jpg', gif_url = 'https://cdn.exercisedb.dev/w/videos/m1Fo8aC/41n2hcw2FN534HcA__Dumbbell-Stiff-Leg-Deadlift_Waist.mp4', exercisedb_id = 'exr_41n2hcw2FN534HcA' WHERE id = 6;
-- [7] Pull-ups → Pull-up (score: 80)
UPDATE exercises SET image_url = 'https://cdn.exercisedb.dev/media/w/images/dweUR5Xhfh.jpg', gif_url = 'https://cdn.exercisedb.dev/w/videos/AYBx4nr/41n2hsBtDXapcADg__Pull-up_Back_.mp4', exercisedb_id = 'exr_41n2hsBtDXapcADg' WHERE id = 7;
-- [11] Seated Cable Row → Seated Row with Towel (score: 40)
UPDATE exercises SET image_url = 'https://cdn.exercisedb.dev/media/w/images/IszXyPAAyK.jpg', gif_url = 'https://cdn.exercisedb.dev/w/videos/RIWAgWd/41n2hcFJpBvAkXCP__Seated-Row-with-Towel_Back.mp4', exercisedb_id = 'exr_41n2hcFJpBvAkXCP' WHERE id = 11;
-- [13] Lateral Raises → Lateral Raise (score: 80)
UPDATE exercises SET image_url = 'https://cdn.exercisedb.dev/media/w/images/KSfBbHaAyy.jpg', gif_url = 'https://cdn.exercisedb.dev/w/videos/j3qqj9g/41n2hjuGpcex14w7__Dumbbell-Lateral-Raise_shoulder_.mp4', exercisedb_id = 'exr_41n2hjuGpcex14w7' WHERE id = 13;
-- [15] Arnold Press → Arnold Press (score: 100)
UPDATE exercises SET image_url = 'https://cdn.exercisedb.dev/media/w/images/4FV9Sfw8CY.jpg', gif_url = 'https://cdn.exercisedb.dev/w/videos/08ys3e3/41n2hMRXm49mM62z__Dumbbell-Arnold-Press-II_Shoulders.mp4', exercisedb_id = 'exr_41n2hMRXm49mM62z' WHERE id = 15;
-- [18] Hammer Curl → Hammer Curl (score: 100)
UPDATE exercises SET image_url = 'https://cdn.exercisedb.dev/media/w/images/2KROa3h5vY.jpg', gif_url = 'https://cdn.exercisedb.dev/w/videos/nuYT8c2/41n2hGioS8HumEF7__Cable-Hammer-Curl-(with-rope)-(male)_Forearms_.mp4', exercisedb_id = 'exr_41n2hGioS8HumEF7' WHERE id = 18;
-- [25] Leg Curl → Lying Double Legs Biceps Curl with Towel (score: 60)
UPDATE exercises SET image_url = 'https://cdn.exercisedb.dev/media/w/images/jBEnhOxreg.jpg', gif_url = 'https://cdn.exercisedb.dev/w/videos/Z80fRjW/41n2hc2VrB8ofxrW__Lying-Double-Legs-Biceps-Curl-with-Towel_Upper-Arms.mp4', exercisedb_id = 'exr_41n2hc2VrB8ofxrW' WHERE id = 25;
-- [27] Bulgarian Split Squat → Bulgarian Split Squat (score: 100)
UPDATE exercises SET image_url = 'https://cdn.exercisedb.dev/media/w/images/8MGbQWUwkt.jpg', gif_url = 'https://cdn.exercisedb.dev/w/videos/bn2Y6tf/41n2hpLLs1uU5atr__Bulgarian-Split-Squat_Thighs.mp4', exercisedb_id = 'exr_41n2hpLLs1uU5atr' WHERE id = 27;
-- [29] Romanian Deadlift → Romanian Deadlift (score: 100)
UPDATE exercises SET image_url = 'https://cdn.exercisedb.dev/media/w/images/D04e3dSK89.jpg', gif_url = 'https://cdn.exercisedb.dev/w/videos/sZiAup2/41n2hn8rpbYihzEW__Dumbbell-Romanian-Deadlift_Hips.mp4', exercisedb_id = 'exr_41n2hn8rpbYihzEW' WHERE id = 29;
-- [30] Plank → Front Plank with Leg Lift  (score: 80)
UPDATE exercises SET image_url = 'https://cdn.exercisedb.dev/media/w/images/KtvnpKaSIO.jpg', gif_url = 'https://cdn.exercisedb.dev/w/videos/AkFLKka/41n2hKoQnnSRPZrE__Front-Plank-with-Leg-Lift-(male)_Hips_.mp4', exercisedb_id = 'exr_41n2hKoQnnSRPZrE' WHERE id = 30;
-- [34] Decline Bench Press → Bench Press (score: 80)
UPDATE exercises SET image_url = 'https://cdn.exercisedb.dev/media/w/images/MKspzx3H3T.jpg', gif_url = 'https://cdn.exercisedb.dev/w/videos/N75Uemp/41n2hxnFMotsXTj3__Barbell-Bench-Press_Chest2_.mp4', exercisedb_id = 'exr_41n2hxnFMotsXTj3' WHERE id = 34;
-- [36] Push-ups → Push-up (score: 80)
UPDATE exercises SET image_url = 'https://cdn.exercisedb.dev/media/w/images/ZVZe7lmc7O.jpg', gif_url = 'https://cdn.exercisedb.dev/w/videos/G8ZH9KB/41n2hNXJadYcfjnd__Push-up-m_Chest.mp4', exercisedb_id = 'exr_41n2hNXJadYcfjnd' WHERE id = 36;
-- [37] Incline Barbell Press → Dumbbell Incline One Arm Hammer Press (score: 40)
UPDATE exercises SET image_url = 'https://cdn.exercisedb.dev/media/w/images/EEeXEu5x2b.jpg', gif_url = 'https://cdn.exercisedb.dev/w/videos/cCtHUc4/41n2haNJ3NA8yCE2__Dumbbell-Incline-One-Arm-Hammer-Press_Upper-Arms_.mp4', exercisedb_id = 'exr_41n2haNJ3NA8yCE2' WHERE id = 37;
-- [40] Flat Dumbbell Press → Dumbbell Incline One Arm Hammer Press (score: 40)
UPDATE exercises SET image_url = 'https://cdn.exercisedb.dev/media/w/images/EEeXEu5x2b.jpg', gif_url = 'https://cdn.exercisedb.dev/w/videos/cCtHUc4/41n2haNJ3NA8yCE2__Dumbbell-Incline-One-Arm-Hammer-Press_Upper-Arms_.mp4', exercisedb_id = 'exr_41n2haNJ3NA8yCE2' WHERE id = 40;
-- [45] Back Hyperextension → Hyperextension (score: 80)
UPDATE exercises SET image_url = 'https://cdn.exercisedb.dev/media/w/images/x6jmdZRn6o.jpg', gif_url = 'https://cdn.exercisedb.dev/w/videos/2aScjba/41n2hfYD2sH4TRCH__Hyperextension_Waist.mp4', exercisedb_id = 'exr_41n2hfYD2sH4TRCH' WHERE id = 45;
-- [48] Chin-up → Chin-ups (score: 80)
UPDATE exercises SET image_url = 'https://cdn.exercisedb.dev/media/w/images/JEvP8CFEdi.jpg', gif_url = 'https://cdn.exercisedb.dev/w/videos/PV80ppW/41n2hd6SThQhAdnZ__Chin-ups-(narrow-parallel-grip)_Back.mp4', exercisedb_id = 'exr_41n2hd6SThQhAdnZ' WHERE id = 48;
-- [49] Dumbbell Deadlift → Dumbbell Stiff Leg Deadlift (score: 60)
UPDATE exercises SET image_url = 'https://cdn.exercisedb.dev/media/w/images/5zfJekr2FH.jpg', gif_url = 'https://cdn.exercisedb.dev/w/videos/m1Fo8aC/41n2hcw2FN534HcA__Dumbbell-Stiff-Leg-Deadlift_Waist.mp4', exercisedb_id = 'exr_41n2hcw2FN534HcA' WHERE id = 49;
-- [50] Seated Dumbbell Press → Dumbbell Incline One Arm Hammer Press (score: 40)
UPDATE exercises SET image_url = 'https://cdn.exercisedb.dev/media/w/images/EEeXEu5x2b.jpg', gif_url = 'https://cdn.exercisedb.dev/w/videos/cCtHUc4/41n2haNJ3NA8yCE2__Dumbbell-Incline-One-Arm-Hammer-Press_Upper-Arms_.mp4', exercisedb_id = 'exr_41n2haNJ3NA8yCE2' WHERE id = 50;
-- [51] Front Raise → Front Raise (score: 100)
UPDATE exercises SET image_url = 'https://cdn.exercisedb.dev/media/w/images/QqA1I6609c.jpg', gif_url = 'https://cdn.exercisedb.dev/w/videos/s0tBYjQ/41n2howQHvcrcrW6__Dumbbell-Front-Raise_Shoulders.mp4', exercisedb_id = 'exr_41n2howQHvcrcrW6' WHERE id = 51;
-- [52] Cable Lateral Raise → Lateral Raise (score: 80)
UPDATE exercises SET image_url = 'https://cdn.exercisedb.dev/media/w/images/KSfBbHaAyy.jpg', gif_url = 'https://cdn.exercisedb.dev/w/videos/j3qqj9g/41n2hjuGpcex14w7__Dumbbell-Lateral-Raise_shoulder_.mp4', exercisedb_id = 'exr_41n2hjuGpcex14w7' WHERE id = 52;
-- [53] Standing Dumbbell Press → Dumbbell Incline One Arm Hammer Press (score: 40)
UPDATE exercises SET image_url = 'https://cdn.exercisedb.dev/media/w/images/EEeXEu5x2b.jpg', gif_url = 'https://cdn.exercisedb.dev/w/videos/cCtHUc4/41n2haNJ3NA8yCE2__Dumbbell-Incline-One-Arm-Hammer-Press_Upper-Arms_.mp4', exercisedb_id = 'exr_41n2haNJ3NA8yCE2' WHERE id = 53;
-- [54] Rear Delt Fly → Dumbbell Rear Delt Fly  (score: 80)
UPDATE exercises SET image_url = 'https://cdn.exercisedb.dev/media/w/images/wMOZasduhs.jpg', gif_url = 'https://cdn.exercisedb.dev/w/videos/FlYe7Y5/41n2hyNf5GebszTf__Dumbbell-Rear-Delt-Fly-(female)_Shoulders.mp4', exercisedb_id = 'exr_41n2hyNf5GebszTf' WHERE id = 54;
-- [57] Incline Dumbbell Curl → Dumbbell Incline One Arm Hammer Press (score: 40)
UPDATE exercises SET image_url = 'https://cdn.exercisedb.dev/media/w/images/EEeXEu5x2b.jpg', gif_url = 'https://cdn.exercisedb.dev/w/videos/cCtHUc4/41n2haNJ3NA8yCE2__Dumbbell-Incline-One-Arm-Hammer-Press_Upper-Arms_.mp4', exercisedb_id = 'exr_41n2haNJ3NA8yCE2' WHERE id = 57;
-- [59] Concentration Curl → Biceps Leg Concentration Curl (score: 80)
UPDATE exercises SET image_url = 'https://cdn.exercisedb.dev/media/w/images/4IzceQy0QK.jpg', gif_url = 'https://cdn.exercisedb.dev/w/videos/kaolGLQ/41n2hxqpSU5p6DZv__Biceps-Leg-Concentration-Curl_Upper-Arms.mp4', exercisedb_id = 'exr_41n2hxqpSU5p6DZv' WHERE id = 59;
-- [62] Reverse Barbell Curl → Two Legs Reverse Biceps Curl with Towel  (score: 40)
UPDATE exercises SET image_url = 'https://cdn.exercisedb.dev/media/w/images/EgzDjmD1Tz.jpg', gif_url = 'https://cdn.exercisedb.dev/w/videos/UBucvJE/41n2hx6oyEujP1B6__Two-Legs-Reverse-Biceps-Curl-with-Towel-(VERSION-2).mp4', exercisedb_id = 'exr_41n2hx6oyEujP1B6' WHERE id = 62;
-- [67] Close Grip Bench Press → Bench Press (score: 80)
UPDATE exercises SET image_url = 'https://cdn.exercisedb.dev/media/w/images/MKspzx3H3T.jpg', gif_url = 'https://cdn.exercisedb.dev/w/videos/N75Uemp/41n2hxnFMotsXTj3__Barbell-Bench-Press_Chest2_.mp4', exercisedb_id = 'exr_41n2hxnFMotsXTj3' WHERE id = 67;
-- [70] Diamond Push-up → Diamond Push-up (score: 100)
UPDATE exercises SET image_url = 'https://cdn.exercisedb.dev/media/w/images/1TQ8mvQq8X.jpg', gif_url = 'https://cdn.exercisedb.dev/w/videos/OltRdJo/41n2hRZ6fgsLyd77__Diamond-Push-up_Upper-Arms.mp4', exercisedb_id = 'exr_41n2hRZ6fgsLyd77' WHERE id = 70;
-- [71] Goblet Squat → Goblet Squat (score: 100)
UPDATE exercises SET image_url = 'https://cdn.exercisedb.dev/media/w/images/8IkHBRnk4P.jpg', gif_url = 'https://cdn.exercisedb.dev/w/videos/nFmXQAf/41n2hQDiSwTZXM4F__Dumbbell-Goblet-Squat_Thighs.mp4', exercisedb_id = 'exr_41n2hQDiSwTZXM4F' WHERE id = 71;
-- [72] Front Squat → Squat (score: 80)
UPDATE exercises SET image_url = 'https://cdn.exercisedb.dev/media/w/images/qYjXvLknoh.jpg', gif_url = 'https://cdn.exercisedb.dev/w/videos/OCSQUGO/41n2hmGR8WuVfe1U__Bodyweight-Squat-(male)_Thighs-SIDE-POV_.mp4', exercisedb_id = 'exr_41n2hmGR8WuVfe1U' WHERE id = 72;
